# Generated by Django 5.1.1 on 2024-10-15 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='sales',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='date_bought',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='quantity_in_stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='quantity_sold',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
