# Generated by Django 5.1.1 on 2024-10-15 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_inventory_sales_alter_inventory_date_bought_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='profit_loss',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
