# Generated by Django 5.1.1 on 2024-11-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_inventory_profit_loss'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='quantity_remaining',
            field=models.PositiveBigIntegerField(default=0, max_length=10),
        ),
    ]
