# Generated by Django 5.1.1 on 2024-11-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_inventory_quantity_remaining'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='quantity_remaining',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
